# Use this file to configure the Overcommit hooks you wish to use. This will
# extend the default configuration defined in:
# https://github.com/sds/overcommit/blob/master/config/default.yml
#
# At the topmost level of this YAML file is a key representing type of hook
# being run (e.g. pre-commit, commit-msg, etc.). Within each type you can
# customize each hook, such as whether to only run it on certain files (via
# `include`), whether to only display output if it fails (via `quiet`), etc.
#
# For a complete list of hooks, see:
# https://github.com/sds/overcommit/tree/master/lib/overcommit/hook
#
# For a complete list of options that you can use to customize hooks, see:
# https://github.com/sds/overcommit#configuration
#
# Uncomment the following lines to make the configuration take effect.

PostCheckout:
  BundleInstall:
    enabled: true

PreCommit:
  AuthorName:
    enabled: false
  EsLint:
    enabled: true
    required_executable: "yarn"
    command: ["yarn", "eslint", "app/javascript/**/*.js"]
    flags: []
  MergeConflicts:
    enabled: true
  RuboCop:
    enabled: true
    on_warn: fail
    command: ["bundle", "exec", "rubocop"]
  ErbLint:
    enabled: true
    description: "Analyze with ERB Lint"
    required_executable: "erblint"
    install_command: "bundle install erb_lint"
    include: "**/*.html.erb"
  Reek:
    enabled: true
    description: "Analyze with Reek"
    required_executable: "reek"
    flags: ["--single-line", "--no-color", "--force-exclusion"]
    install_command: "gem install reek"
    include:
      - "**/*.gemspec"
      - "**/*.rake"
      - "**/*.rb"
      - "**/Gemfile"
      - "**/Rakefile"
  # RSpec:
  #   enabled: true
  #   description: 'Run RSpec test suite'
  #   required_executable: 'bundle exec rspec'
CommitMsg:
  CapitalizedSubject:
    enabled: false
  MessageFormat:
    enabled: true
    description: "Check commit message matches expected pattern"
    pattern: ^(?<type>build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test|¯\\_\(ツ\)_\/¯)(?<scope>\(\w+\)?((?=:\s)|(?=!:\s)))?(?<breaking>!)?(?<subject>:\s.*)?|^(?<merge>Merge \w+)
    expected_pattern_message: '(type)(?scope):\s(message)'
    sample_message: "feat(user): add jwt auth"
  TextWidth:
    enabled: true
    min_subject_width: 8 # three 2-letter words with 2 spaces
    max_subject_width: 72
    quiet: false
  EmptyMessage:
    enabled: true
    required: true
