---
# detectors:
#   InstanceVariableAssumption:
#     enabled: false
directories:
  "**/app/controllers":
    IrresponsibleModule:
      enabled: false
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
    TooManyInstanceVariables:
      enabled: false
  "**/app/controllers/users":
    IrresponsibleModule:
      enabled: false
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
  "**/app/helpers":
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
  "**/app/mailers":
    InstanceVariableAssumption:
      enabled: false
  "**/app/models":
    InstanceVariableAssumption:
      enabled: false
  "**/db/migrate":
    UncommunicativeVariableName:
      enabled: false
    TooManyStatements:
      enabled: false
    IrresponsibleModule:
      enabled: false
    FeatureEnvy:
      enabled: false
    DuplicateMethodCall: # correctness is more important in migration files
      enabled: false
    UtilityFunction:
      enabled: false
