require:
  - standard
  - rubocop-rspec
  - rubocop-rails

inherit_gem:
  standard: config/base.yml

AllCops:
  Exclude:
    - vendor/**/*.rb # or vendor/bundle/**/*
  TargetRubyVersion: 3.0.3
  NewCops: enable

Style/RedundantReturn:
  Exclude:
    - app/controllers/**/*

RSpec/FilePath:
  Enabled: false # bug

Rails/RakeEnvironment:
  Exclude:
    - lib/tasks/docker/*.rake
