version: "3"
services:
  web:
    build: .
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    environment:
      RAILS_ENV: development
      PG_HOST: postgres
      PG_USERNAME: postgres
      PG_PASSWORD: postgres
      REDIS_URL: redis://redis:6379/1
    ports:
      - "3000:3000"
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:14.4-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis:7.0.4-alpine

volumes:
  pg_data:
  redis_data:
  bundle: