require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/user_files" do
  # This should return the minimal set of attributes required to create a valid
  # UserFile. As you add validations to UserFile, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      UserFile.create! valid_attributes
      get user_files_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      user_file = UserFile.create! valid_attributes
      get user_file_url(user_file)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_user_file_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      user_file = UserFile.create! valid_attributes
      get edit_user_file_url(user_file)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new UserFile" do
        expect {
          post user_files_url, params: {user_file: valid_attributes}
        }.to change(UserFile, :count).by(1)
      end

      it "redirects to the created user_file" do
        post user_files_url, params: {user_file: valid_attributes}
        expect(response).to redirect_to(user_file_url(UserFile.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new UserFile" do
        expect {
          post user_files_url, params: {user_file: invalid_attributes}
        }.not_to change(UserFile, :count)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post user_files_url, params: {user_file: invalid_attributes}
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested user_file" do
        user_file = UserFile.create! valid_attributes
        patch user_file_url(user_file), params: {user_file: new_attributes}
        user_file.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the user_file" do
        user_file = UserFile.create! valid_attributes
        patch user_file_url(user_file), params: {user_file: new_attributes}
        user_file.reload
        expect(response).to redirect_to(user_file_url(user_file))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        user_file = UserFile.create! valid_attributes
        patch user_file_url(user_file), params: {user_file: invalid_attributes}
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested user_file" do
      user_file = UserFile.create! valid_attributes
      expect {
        delete user_file_url(user_file)
      }.to change(UserFile, :count).by(-1)
    end

    it "redirects to the user_files list" do
      user_file = UserFile.create! valid_attributes
      delete user_file_url(user_file)
      expect(response).to redirect_to(user_files_url)
    end
  end
end
